version: '3'

services:
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
    networks:
      - app-network
    ports:
      - 15672:15672
      - 5672:5672

networks:
  app-network:
    driver: bridge
